In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [3]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])

In [4]:
x

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55]])

In [6]:
y

array([ 5, 20, 14, 32, 22, 38])

In [8]:
print(x.shape)
y.shape

(6, 1)


(6,)

In [9]:
model = LinearRegression()

In [10]:
model.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [11]:
model = LinearRegression().fit(x, y)

In [12]:
r_sq = model.score(x, y)

In [13]:
r_sq

0.715875613747954

In [18]:
print('intercept' + str(model.intercept_))
print('Slope' + str(model.coef_))

intercept5.633333333333329
Slope[0.54]


In [20]:
new_model = LinearRegression().fit(x, y.reshape((-1, 1)))

In [21]:
print('intercept' + str(new_model.intercept_))
print('Slope' + str(new_model.coef_))

intercept[5.63333333]
Slope[[0.54]]


In [22]:
y_pred = model.predict(x)

In [23]:
y_pred

array([ 8.33333333, 13.73333333, 19.13333333, 24.53333333, 29.93333333,
       35.33333333])

In [24]:
y_pred = model.intercept_ + model.coef_ * x

In [25]:
y_pred

array([[ 8.33333333],
       [13.73333333],
       [19.13333333],
       [24.53333333],
       [29.93333333],
       [35.33333333]])

In [26]:
x_new = np.arange(5).reshape((-1, 1))

In [27]:
y_new = model.predict(x_new)

In [28]:
y_new

array([5.63333333, 6.17333333, 6.71333333, 7.25333333, 7.79333333])

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)

In [30]:
print(x)

[[ 0  1]
 [ 5  1]
 [15  2]
 [25  5]
 [35 11]
 [45 15]
 [55 34]
 [60 35]]


In [2]:
model = LinearRegression().fit(x, y)

In [3]:
r_sq = model.score(x, y)

In [4]:
print('coefficient of determination:', r_sq)
print('intercept:', model.intercept_)
print('slope:', model.coef_)
x_ = PolynomialFeatures(degree=2, include_bias=True).fit_transform(x)

coefficient of determination: 0.8615939258756776
intercept: 5.52257927519819
slope: [0.44706965 0.25502548]


In [5]:
y_pred = model.predict(x)
print('predicted response:', y_pred, sep='\n')

predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [6]:
x_new = np.arange(10).reshape((-1, 2))
print(x_new)
y_new = model.predict(x_new)
print(y_new)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[ 5.77760476  7.18179502  8.58598528  9.99017554 11.3943658 ]


In [8]:
##"Polynomial Regression With scikit-learn"

In [9]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [10]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([15, 11, 2, 8, 25, 32])

In [11]:
transformer = PolynomialFeatures(degree=2, include_bias=False)

In [12]:
transformer.fit(x)

PolynomialFeatures(degree=2, include_bias=False, interaction_only=False,
                   order='C')

In [13]:
x_ = transformer.transform(x)

In [14]:
x_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x)

In [15]:
x_


array([[   5.,   25.],
       [  15.,  225.],
       [  25.,  625.],
       [  35., 1225.],
       [  45., 2025.],
       [  55., 3025.]])

In [16]:
model = LinearRegression().fit(x_, y)

In [17]:
r_sq = model.score(x_, y)

In [18]:
print('coefficient of determination:', r_sq)

coefficient of determination: 0.8908516262498564


In [19]:
print('intercept:', model.intercept_)

intercept: 21.372321428571425


In [20]:
print('coefficients:', model.coef_)

coefficients: [-1.32357143  0.02839286]


In [21]:
x_ = PolynomialFeatures(degree=2, include_bias=True).fit_transform(x)

In [22]:
x_

array([[1.000e+00, 5.000e+00, 2.500e+01],
       [1.000e+00, 1.500e+01, 2.250e+02],
       [1.000e+00, 2.500e+01, 6.250e+02],
       [1.000e+00, 3.500e+01, 1.225e+03],
       [1.000e+00, 4.500e+01, 2.025e+03],
       [1.000e+00, 5.500e+01, 3.025e+03]])

In [23]:
model = LinearRegression(fit_intercept=False).fit(x_, y)

In [24]:
print('coefficient of determination:', r_sq)
print('intercept:', model.intercept_)
print('coefficients:', model.coef_)

coefficient of determination: 0.8908516262498564
intercept: 0.0
coefficients: [21.37232143 -1.32357143  0.02839286]


In [25]:
y_pred = model.predict(x_)
print('predicted response:', y_pred, sep='\n')

predicted response:
[15.46428571  7.90714286  6.02857143  9.82857143 19.30714286 34.46428571]


In [26]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [27]:
# Step 2a: Provide data
x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)

# Step 2b: Transform input data
x_ = PolynomialFeatures(degree=2, include_bias=False).fit_transform(x)

# Step 3: Create a model and fit it
model = LinearRegression().fit(x_, y)

# Step 4: Get results
r_sq = model.score(x_, y)
intercept, coefficients = model.intercept_, model.coef_

# Step 5: Predict
y_pred = model.predict(x_)

In [28]:
print('coefficient of determination:', r_sq)
print('intercept:', intercept)
print('coefficients:', coefficients, sep='\n')
print('predicted response:', y_pred, sep='\n')

coefficient of determination: 0.9453701449127822
intercept: 0.8430556452395734
coefficients:
[ 2.44828275  0.16160353 -0.15259677  0.47928683 -0.4641851 ]
predicted response:
[ 0.54047408 11.36340283 16.07809622 15.79139    29.73858619 23.50834636
 39.05631386 41.92339046]


In [29]:
#Advanced Linear Regression With statsmodels

In [35]:
import numpy as np
import statsmodels.api as sm

In [36]:
x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)

In [37]:
x = sm.add_constant(x)

In [38]:
x

array([[ 1.,  0.,  1.],
       [ 1.,  5.,  1.],
       [ 1., 15.,  2.],
       [ 1., 25.,  5.],
       [ 1., 35., 11.],
       [ 1., 45., 15.],
       [ 1., 55., 34.],
       [ 1., 60., 35.]])

In [39]:
y

array([ 4,  5, 20, 14, 32, 22, 38, 43])

In [40]:
model = sm.OLS(y, x)

In [41]:
results = model.fit()

In [42]:
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.862
Model:                            OLS   Adj. R-squared:                  0.806
Method:                 Least Squares   F-statistic:                     15.56
Date:                Sat, 25 Jul 2020   Prob (F-statistic):            0.00713
Time:                        13:06:14   Log-Likelihood:                -24.316
No. Observations:                   8   AIC:                             54.63
Df Residuals:                       5   BIC:                             54.87
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          5.5226      4.431      1.246      0.2

C:\ProgramData\Anaconda3\lib\site-packages\scipy\stats\stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  "anyway, n=%i" % int(n))


In [43]:
print('coefficient of determination:', results.rsquared)
print('adjusted coefficient of determination:', results.rsquared_adj)
print('regression coefficients:', results.params)

coefficient of determination: 0.8615939258756777
adjusted coefficient of determination: 0.8062314962259488
regression coefficients: [5.52257928 0.44706965 0.25502548]


In [44]:
print('predicted response:', results.fittedvalues, sep='\n')
print('predicted response:', results.predict(x), sep='\n')

predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]
predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [46]:
print(x_new)
y_new = results.predict(x_new)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


ValueError: shapes (5,2) and (3,) not aligned: 2 (dim 1) != 3 (dim 0)